---

- include: install.yml
  when: not orchestrator_rolesonly

- block:
    - name: recover github ansible roles
      git:
        repo: "{{ item.url }}"
        dest: "{{ item.p }}"
        update: yes
        version: "{{ item.v | default('HEAD') }}"
      with_items: "{{ orchestrator_github_roles }}"
  when: orchestrator_github_roles is defined and orchestrator_github_roles != []

- block:
    - name: recover galaxy ansible roles
      command: "ansible-galaxy install {{ item.n }} -p {{ item.p }}"
      with_items: "{{ orchestrator_galaxy_roles }}"
  when: orchestrator_galaxy_roles is defined and orchestrator_galaxy_roles != []
