---
# https://learn.microsoft.com/en-us/cli/azure/install-azure-cli-linux

- name: Add Microsoft Apt signing key
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Ensure Microsoft Azure repository is present
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release | lower }} main"
    filename: azure-cli
    state: present
  notify:
    - Update apt cache

- name: Flush handlers
  ansible.builtin.meta: flush_handlers
