---

- name: Redhat | orchestrator tools
  ansible.builtin.yum:
    name: "{{ orchestrator_pkg }}"
    state: "present"
    update_cache: "yes"
  register: pkg_result
  until: pkg_result is success

- name: Download vagrant
  ansible.builtin.get_url:
    url: "{{ orchestrator_vagrant_url_rpm }}"
    dest: "{{ install_archives }}/{{ orchestrator_vagrant_url_rpm | basename }}"
    checksum: "{{ orchestrator_vagrant_url_rpm_hash }}"
    mode: '0644'

- name: Import hashicorp gpg key
  ansible.builtin.rpm_key:
    state: present
    key: https://rpm.releases.hashicorp.com/gpg

- name: Install vagrant
  ansible.builtin.yum:
    name: "{{ install_archives }}/{{ orchestrator_vagrant_url_rpm | basename }}"
    state: present
    disable_gpg_check: "{{ orchestrator_yum_disable_gpg_check | default(omit) }}"
  register: pkg_result
  until: pkg_result is success
