---

- name: yum | orchestrator tools
  yum: name={{ orchestrator_pkg }} state=present update_cache=yes
  register: pkg_result
  until: pkg_result is success

- name: Download vagrant
  get_url:
    url: "{{ orchestrator_vagrant_url_rpm }}"
    dest: "{{ install_archives }}/{{ orchestrator_vagrant_url_rpm | basename }}"
    checksum: "{{ orchestrator_vagrant_url_rpm_hash }}"

- name: Install vagrant
  yum: "name={{ install_archives }}/{{ orchestrator_vagrant_url_rpm | basename }}"
  register: pkg_result
  until: pkg_result is success
