---

- name: Verify
  hosts: o
  tasks:
  - name: Validate ansible
    ansible.builtin.command: ansible --version  # noqa 303
    changed_when: false
    register: v1
  - name: Validate ansible
    ansible.builtin.assert:
      that: v1.rc == 0
